import { GREEN_COLOR, RED_COLOR, BLACK_COLOR } from "./constants/colors";

export const data = [
  { option: 0, style: { backgroundColor: GREEN_COLOR } },
  { option: 32, style: { backgroundColor: RED_COLOR } },
  { option: 15, style: { backgroundColor: BLACK_COLOR } },
  { option: 19, style: { backgroundColor: RED_COLOR } },
  { option: 4, style: { backgroundColor: BLACK_COLOR } },
  { option: 21, style: { backgroundColor: RED_COLOR } },
  { option: 2, style: { backgroundColor: BLACK_COLOR } },
  { option: 25, style: { backgroundColor: RED_COLOR } },
  { option: 17, style: { backgroundColor: BLACK_COLOR } },
  { option: 34, style: { backgroundColor: RED_COLOR } },
  { option: 6, style: { backgroundColor: BLACK_COLOR } },
  { option: 27, style: { backgroundColor: RED_COLOR } },
  { option: 13, style: { backgroundColor: BLACK_COLOR } },
  { option: 36, style: { backgroundColor: RED_COLOR } },
  { option: 11, style: { backgroundColor: BLACK_COLOR } },
  { option: 30, style: { backgroundColor: RED_COLOR } },
  { option: 8, style: { backgroundColor: BLACK_COLOR } },
  { option: 23, style: { backgroundColor: RED_COLOR } },
  { option: 10, style: { backgroundColor: BLACK_COLOR } },
  { option: 5, style: { backgroundColor: RED_COLOR } },
  { option: 24, style: { backgroundColor: BLACK_COLOR } },
  { option: 16, style: { backgroundColor: RED_COLOR } },
  { option: 33, style: { backgroundColor: BLACK_COLOR } },
  { option: 1, style: { backgroundColor: RED_COLOR } },
  { option: 20, style: { backgroundColor: BLACK_COLOR } },
  { option: 14, style: { backgroundColor: RED_COLOR } },
  { option: 31, style: { backgroundColor: BLACK_COLOR } },
  { option: 9, style: { backgroundColor: RED_COLOR } },
  { option: 22, style: { backgroundColor: BLACK_COLOR } },
  { option: 18, style: { backgroundColor: RED_COLOR } },
  { option: 29, style: { backgroundColor: BLACK_COLOR } },
  { option: 7, style: { backgroundColor: RED_COLOR } },
  { option: 28, style: { backgroundColor: BLACK_COLOR } },
  { option: 12, style: { backgroundColor: RED_COLOR } },
  { option: 35, style: { backgroundColor: BLACK_COLOR } },
  { option: 3, style: { backgroundColor: RED_COLOR } },
  { option: 26, style: { backgroundColor: BLACK_COLOR } },
];
